[project]
name = "zomato-data-engineering-project"
version = "0.1.0"
description = "Zomato Data Engineering Pipeline with Airflow, dbt, and Snowflake"
readme = "README.md"
authors = [
    { name = "Tanay Jujarao", email = "tanayjujarao@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.0",
    "dbt-snowflake>=1.12.0",
    "google-genai>=2.21.0",
    "python-dotenv>=1.2.3",
    "snowflake-connector-python>=4.7.2",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"